# Base configs
baseurl: "https://github.com/sunrafunk/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Sun Ra"
subtitle: "This is Her"
author: "Oxun Sun Ra Bravo"
header:
 title: "Photography"
 subtitle: "by Sun Ra"
footer:
 name: "Hey there, my name is Sun"
 bio: "I'm just a black spade spawn out the nebula"
social_urls:
  twitter: ""https://www.twitter.com/kungfuluul"
  